openapi: 3.0.3
info:
  title: Arena Technical Test API
  version: 1.0.0

servers:
  - url: /api

paths:
  /:
    get:
      summary: test route to check if server running
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: string
                example: 'hello world'
  /latest-tx:
    post:
      summary: returns the latest transaction for a given wallet address on a given contract
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              properties:
                contract_address:
                  type: string
                wallet_address:
                  type: string
      responses:
        200:
          description: return transaction object
        400:
          description: invalid wallet or contract address
        500:
          description: internal server error
  /most-tx:
    post:
      summary: returns the wallet address with the most transactions on a given contract
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              properties:
                contract_address:
                  type: string
                wallets:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: return num of tx on given contract by wallet, sorted by most tx
        400:
          description: invalid wallet or contract address
        500:
          description: internal server error
  /most-used-contract:
    post:
      summary: returns the contract address with the most interactions for a given wallet
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              properties:
                wallet_address:
                  type: string
      responses:
        200:
          description: returns contract address
        400:
          description: invalid wallet address
        500:
          description: internal server error
